### ISSUE TITLE
How to change the color of the cursor?

### ISSUE THREAD

**Issue by lalitendraswamy** [dshongphuc/magic-mouse-js#55]

**Comment by dshongphuc** [comment]
Hey you can change color by CSS, check the class name and just update css for it

**Comment by lalitendraswamy** [comment]
Class name for my div container, or is there any class name for magic-mouse-js?
[Here is my repo link ]( https://github.com/lalitendraswamy/personal-branding.git )

**Comment by rajmondx** [comment]
```css
#magicPointer {
  background: #fff !important;
}

#magicMouseCursor {
  border: 1px solid #fff !important;
}
```

Note. its better to overwrite directly the css instead of using `!important`;
